# Input files
metadata_file: "/lustre/scratch124/humgen/projects_v2/cardinal_analysis/analysis/pb22/final_outputs/metadata_rasqualpipe.tsv"
peaks_file: "/lustre/scratch124/humgen/projects_v2/cardinal_analysis/analysis/pb22/final_outputs/peak_table.tsv"
bam_column: "bamfile"
reference_genome: "/nfs/srpipe_references/downloaded_from_10X/refdata-cellranger-arc-GRCh38-2020-A-2.0.0/fasta/genome.fa"
vcf_regex: "/lustre/scratch124/humgen/projects_v2/cardinal_analysis/analysis/pb22/rasqual_qtl/vcf/vcfs_filt_renamed/*gz"

# Output folder
output_folder: "output_wasp"

# Non-conda tool paths
scar_dir: "scar"
wasp_dir: "WASP"
run_wasp: True  # Set to False to skip WASP processing

# Parameters for scar
min_cells: 10
celltype_column: "celltypes_LEV2"
remove_duplicates: False # Set to True to remove duplicates with scar
